
- name: Check if kubectl can reach the cluster before proceeding
  shell: |
    export KUBECONFIG={{ kubectl_config }}
    {{kubectl_binary}} get nodes
  register: kubectl_status
  failed_when: kubectl_status.rc != 0
  changed_when: false
  retries: 10
  delay: 5
  until: kubectl_status.rc == 0

- name: Install SMB CSI driver in the kube-system namespace
  shell: |
    export KUBECONFIG={{ kubectl_config }}
    git clone https://github.com/kubernetes-csi/csi-driver-smb.git
    {{kubectl_binary}} apply -f csi-driver-smb/deploy/rbac-csi-smb.yaml
    {{kubectl_binary}} apply -f csi-driver-smb/deploy/csi-smb-driver.yaml
    {{kubectl_binary}} apply -f csi-driver-smb/deploy/csi-smb-node.yaml
  register: kubectl_status
  failed_when: kubectl_status.rc != 0
  changed_when: false
  retries: 10
  delay: 5
  until: kubectl_status.rc == 0
